apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: faulty-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: faulty-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: faulty-app
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep 1000
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: faulty-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
