apiVersion: apps/v1
kind: Deployment
metadata:
  name: faulty-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faulty-app
  template:
    metadata:
      labels:
        app: faulty-app
    spec:
      containers:
      - name: faulty-container
        image: busybox:lat
        command: ["/bin/sh", "-c", "sleep 1000"]  