apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    model: gpt-4o-mini
    backend: openai
    secret:
      name: k8sgpt-sample-secret
      key: openai-api-key
    backOff:
      enabled: false  
    anonymized: false
    language: english
  noCache: true
  version: v0.3.50
  filters:
    - Deployment
    - Pod
    - ReplicaSet
  