apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    model: gpt-4o-mini
    backend: openai
    secret:
      name: k8sgpt-sample-secret
      key: openai-api-key
    # anonymized: false
    # language: english
  noCache: false
  version: v0.3.41
  filters:
    - Deployment
    - Pod
  sink:
    type: webhook
    webhook: http://remediation-server.k8sgptclient.svc.cluster.local:9090/webhook
  extraOptions:
    backstage:
      enabled: true