apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: null
  labels:
    app: athutest-servicemonitor
    prometheus: monitoring
  name: athutest-servicemonitor
  namespace: default
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
  namespaceSelector: {}
  selector:
    matchLabels:
      app: athutest
