apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-server
  namespace: k8sgptclient
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remediation-server
rules:
- apiGroups: ["core.k8sgpt.ai"]
  resources: ["results"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remediation-server
subjects:
- kind: ServiceAccount
  name: remediation-server
  namespace: k8sgptclient
roleRef:
  kind: ClusterRole
  name: remediation-server
  apiGroup: rbac.authorization.k8s.io