apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-server
  namespace: k8sgptclient
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remediation-server
rules:
# For Pod analysis
- apiGroups: [""]  # Core API group
  resources:
    - "pods"
    - "events"     # Required for pod event analysis
  verbs: ["get", "list", "watch"]
# For Deployment analysis
- apiGroups: ["apps"]
  resources:
    - "deployments"
    - "replicasets"  # Required as deployments manage replicasets
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remediation-server
subjects:
- kind: ServiceAccount
  name: remediation-server
  namespace: k8sgptclient
roleRef:
  kind: ClusterRole
  name: remediation-server
  apiGroup: rbac.authorization.k8s.io