apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-server
  namespace: k8sgptclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediation-server
  template:
    metadata:
      labels:
        app: remediation-server
    spec:
      serviceAccountName: remediation-server 
      containers:
      - name: k8sgptclient
        image: sanskardevops/k8sgptclient:latest
        command: ["./k8sgptclient"]
        args: 
        - "serve"
        - "remediation-server"
        - "--config=/etc/k8sgpt/k8sgpt.yaml"
        - "--agent-url=http://k8s-agent.k8sgptclient.svc.cluster.local:8080"
        - "--backend=openai"
        - "--explain=true" 
        volumeMounts:
        - name: k8sgpt-config
          mountPath: /etc/k8sgpt
          readOnly: true
      volumes:
      - name: k8sgpt-config
        configMap:
          name: k8sgpt-config
        