apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-server
  namespace: k8sgptclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediation-server
  template:
    metadata:
      labels:
        app: remediation-server
    spec:
      serviceAccountName: remediation-server 
      containers:
      - name: k8sgptclient
        image: sanskardevops/k8sgptclient:latest
        command: ["./k8sgptclient"]
        args: ["serve", "remediation-server", "--http-address=:9090"]
        ports:
        - containerPort: 9090
        