apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-server
  namespace: k8sgptclient
  labels:
    app: remediation-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediation-server
  template:
    metadata:
      labels:
        app: remediation-server
    spec:
      serviceAccountName: remediation-server 
      containers:
      - name: k8sgpt-remediation
        image: sanskardevops/k8sgpt-remediation:latest
        command: ["/bin/sh", "-c"]
        args: 
        - >
            exec ./k8sgpt-remediation serve remediation-server
            --config=/etc/k8sgpt/k8sgpt.yaml
            --agent-url=http://k8s-agent.k8sgptclient.svc.cluster.local:8080
            --backend=openai
            --explain=true
            --api-key=${API_KEY}
            --no-cache=true
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: k8sgpt-sample-secret
                key: openai-api-key   
        volumeMounts:
        - name: k8sgpt-config
          mountPath: /etc/k8sgpt
          readOnly: true
      volumes:
      - name: k8sgpt-config
        configMap:
          name: k8sgpt-config
        