apiVersion: v1
kind: Secret
metadata:
  name: k8sgpt-sample-secret
  namespace: k8sgptclient
data:
  openai-api-key: c2stc3ZjYWNjdC1sVzQ2TldIb0dSVW54SzhOc3NjTXdwNDlWSEpoV1hKb0xjNkQ3NTgwd3p6eE44MUJqekJWQl9sSFNqV3ZVOV90dkpXeDVsVDNCbGJrRkpSSGs0ZEpsbTZ3eXFBTGRLbGt3ZkRKVnJlc3VsRDNWVHZCSlFPMEZtQ0taUk10b0ZVNG9QOXlQV0VWNW44QzhCdWNBUUVB

