apiVersion: v1
kind: Service
metadata:
  name: remediation-server
  namespace: k8sgptclient
spec:
  selector:
    app: remediation-server
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP