apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgptclient-agent
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: k8s-agent=sanskardevops/k8s-agent:latest
    argocd-image-updater.argoproj.io/k8s-agent.update-strategy: newest-build
spec:
  project: default
  source:
    repoURL: git@github.com:Sanskarzz/k8sgptclient.git 
    targetRevision: main
    path: manifest/k8sgptclient/agent-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgptclient
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true