apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faulty-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sanskarzz/k8sgptclient.git  
    targetRevision: HEAD
    path: manifest/faulty-manifest/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    