apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgptclient-remediation
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: remediation=sanskardevops/k8sgpt-remediation:1.0.0
    argocd-image-updater.argoproj.io/remediation.update-strategy: semver
    argocd-image-updater.argoproj.io/remediation.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/remediation.pull-secret: pullsecret:argocd/dockerhub-secret
spec:
  project: default
  source:
    repoURL: git@github.com:Sanskarzz/k8sgptclient.git 
    targetRevision: main
    path: manifest/k8sgptclient/remediation-server-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgptclient
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true