---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sgptclient
  namespace: k8sgptclient
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sgptclient-role
  namespace: k8sgptclient
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sgptclient-binding
subjects:
- kind: ServiceAccount
  name: k8sgptclient
  namespace: k8sgptclient
roleRef:
  kind: ClusterRole
  name: k8sgptclient-role
  apiGroup: rbac.authorization.k8s.io